### ISSUE TITLE
Provide Some Config Examples

### ISSUE THREAD

**Issue by GloriousSoup** [raspofabs/broadside#12]
Some general config examples would be useful in the following cases:
Integer - From which I can infer any basic type
Vec2 - From which I can infer any simple struct

and finally...
Ship Stats - A config format we can use to bunch together similar qualities for enumerated ship types. What is our strategy here?

A crude example

smallship
{
speed = 2
health = 3
}

largeship
{
speed = 1
health = 6
}

...such that we can reference in code from the enumerator
float mySpeed = speed[ship->eShipType];

**Comment by GloriousSoup** [comment]
Priority 1 because its blocking me from going crazy with the config system!

**Comment by raspofabs** [comment]
done on master. You now have ints, and arrays of float and int. Also, whitespace is ignored, meaning you won't get odd effects like you did with your previous test.
