### ISSUE TITLE
Implement a config file system

### ISSUE THREAD

**Issue by GloriousSoup** [raspofabs/broadside#6]
This will assist in two matters:
 - Faster turnaround in tweaking display elements (I'm imagining live editing a config file alongside the game)
 - Consolidating ship statistics (Currently there are a bunch of static arrays, which is going to quickly become unmanageable as I add more ship stats)

**Comment by GloriousSoup** [comment]
Priority 1 because the later this goes in, the more stuff I'm going to have to re-code to support it.

**Comment by raspofabs** [comment]
sorted. Check out Variables.h and data/test.ini
